# Generated by Django 4.2.23 on 2025-08-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
