# Generated by Django 4.2.23 on 2025-08-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_bot', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Chat Session', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_response',
            field=models.TextField(blank=True),
        ),
    ]
