# Generated by Django 4.2.23 on 2025-08-18 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_bot', '0005_knowledgecategory_pricingplan_restauranttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('demo_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_meet_link', models.URLField(blank=True, null=True)),
                ('google_calendar_link', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
