# Generated by Django 4.2.23 on 2025-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=100)),
                ('resturent', models.CharField(max_length=100)),
                ('monthly_revenue', models.CharField(max_length=100)),
                ('growth', models.CharField(max_length=100)),
            ],
        ),
    ]
