# Generated by Django 4.2.23 on 2025-07-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRestaurantCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
