# Generated by Django 4.2.23 on 2025-07-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('superadmin', '0002_monthlyrestaurantcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('inbound', 'Inbound Call'), ('outbound', 'Outbound Call'), ('missed', 'Missed Call')], max_length=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='authentication.subadminprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
