# Generated by Django 4.2.23 on 2025-07-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('superadmin', '0004_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='call_type',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='callrecord',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_sid',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('failed', 'Failed')], default='in-progress', max_length=20),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='authentication.subadminprofile'),
        ),
    ]
