# Generated by Django 4.2.23 on 2025-07-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_alter_callrecord_options_remove_callrecord_call_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminplan',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminplan',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
