# Generated by Django 4.2.23 on 2025-07-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_adminplan_order_id_adminplan_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminplan',
            old_name='order_id',
            new_name='stripe_checkout_id',
        ),
    ]
