# Generated by Django 4.2.23 on 2025-07-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('superadmin', '0007_rename_order_id_adminplan_stripe_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminplan',
            name='subadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_plans', to='authentication.subadminprofile'),
        ),
    ]
