# Generated by Django 4.2.23 on 2025-07-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('superadmin', '0008_adminplan_subadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminplan',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='adminplan',
            name='stripe_checkout_id',
        ),
        migrations.RemoveField(
            model_name='adminplan',
            name='subadmin',
        ),
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(default='PENDING', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='superadmin.adminplan')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='authentication.subadminprofile')),
            ],
        ),
    ]
