# Generated by Django 4.2.23 on 2025-07-31 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_subscriptionplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='superadmin.subscriptionplan'),
        ),
    ]
