# Generated by Django 4.2.23 on 2025-07-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_alter_planpayment_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPlan',
        ),
    ]
