# Generated by Django 4.2.23 on 2025-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_delete_adminplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
