# Generated by Django 4.2.23 on 2025-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_callrecord_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='caller_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
