# Generated by Django 4.2.23 on 2025-08-12 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0014_callrecord_caller_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpayment',
            name='subadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
