# Generated by Django 4.2.23 on 2025-07-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('trigger_number', models.CharField(help_text='Phone number that customers call', max_length=20)),
                ('greeting_message', models.TextField(default='Welcome to our restaurant!')),
                ('fallback_sms_message', models.TextField(blank=True, null=True)),
                ('working_hours', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('holiday_notice', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_flows', to='authentication.subadminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CallOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keypress', models.CharField(max_length=2)),
                ('label', models.CharField(max_length=255)),
                ('response_message', models.TextField()),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('sms_message', models.TextField(blank=True, null=True)),
                ('call_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='subadmin.callflow')),
            ],
        ),
    ]
