# Generated by Django 4.2.23 on 2025-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callflow',
            name='address',
        ),
        migrations.RemoveField(
            model_name='callflow',
            name='fallback_sms_message',
        ),
        migrations.RemoveField(
            model_name='callflow',
            name='holiday_notice',
        ),
        migrations.RemoveField(
            model_name='callflow',
            name='subadmin',
        ),
        migrations.RemoveField(
            model_name='callflow',
            name='title',
        ),
        migrations.RemoveField(
            model_name='callflow',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='callflow',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='callflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='calloption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='calloption',
            name='return_to_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='callflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='callflow',
            name='greeting_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='callflow',
            name='trigger_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='calloption',
            name='keypress',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='calloption',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='calloption',
            unique_together={('call_flow', 'keypress')},
        ),
    ]
