# Generated by Django 4.2.23 on 2025-07-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0002_remove_callflow_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VapiAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('voice', models.CharField(default='female', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='callflow',
            name='trigger_number',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='CallOption',
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='call_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subadmin.callflow'),
        ),
        migrations.AddField(
            model_name='callflow',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subadmin.vapiassistant'),
        ),
        migrations.AlterUniqueTogether(
            name='callflow',
            unique_together={('trigger_number', 'assistant')},
        ),
    ]
