# Generated by Django 4.2.23 on 2025-07-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('subadmin', '0003_conversationlog_vapiassistant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('closed_all_day', models.BooleanField(default=False)),
                ('subadmin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='authentication.subadminprofile')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('subadmin_profile', 'day')},
            },
        ),
    ]
