# Generated by Django 4.2.23 on 2025-07-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('subadmin', '0004_businesshour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subadmin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='authentication.subadminprofile')),
            ],
        ),
        migrations.AddField(
            model_name='businesshour',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_hours', to='subadmin.menu'),
        ),
    ]
