# Generated by Django 4.2.23 on 2025-07-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('subadmin', '0005_menu_businesshour_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResturent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='subadmin.businesshour')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='subadmin.menu')),
                ('subadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='authentication.subadminprofile')),
            ],
        ),
    ]
