# Generated by Django 4.2.23 on 2025-07-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0006_allresturent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllResturent',
        ),
    ]
