# Generated by Django 4.2.23 on 2025-07-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('subadmin', '0007_delete_allresturent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('ordering', 'Online Ordering'), ('reservation', 'Reservation System'), ('catering', 'Catering Form')], max_length=20)),
                ('provider', models.CharField(choices=[('direct', 'Direct Link'), ('doordash', 'DoorDash'), ('ubereats', 'UberEats'), ('grubhub', 'GrubHub'), ('opentable', 'OpenTable'), ('resy', 'Resy'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='authentication.subadminprofile')),
            ],
            options={
                'ordering': ['link_type', 'provider'],
                'unique_together': {('restaurant', 'link_type', 'provider')},
            },
        ),
    ]
