# Generated by Django 4.2.23 on 2025-07-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_first_name_customuser_last_name'),
        ('subadmin', '0008_restaurantlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSFallbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default="Thank you for calling {restaurant_name}. Our team couldn't process your request through our automated system. A staff member will call you back shortly. For immediate assistance, please call {phone_number} or visit our website at {website_url}.")),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_fallback_settings', to='authentication.subadminprofile')),
            ],
        ),
    ]
