# Generated by Django 4.2.23 on 2025-07-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0009_smsfallbacksettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationlog',
            name='call_flow',
        ),
        migrations.DeleteModel(
            name='CallFlow',
        ),
        migrations.DeleteModel(
            name='ConversationLog',
        ),
        migrations.DeleteModel(
            name='VapiAssistant',
        ),
    ]
