# Generated by Django 4.2.23 on 2025-08-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_subadminprofile_created_at'),
        ('subadmin', '0012_menuitem_usersession_selected_items_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantlink',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantlink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='catering_request_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='direct_ordering_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='direct_reservation_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='doordash_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='grubhub_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='opentable_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='restaurant_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_links', to='authentication.subadminprofile'),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='resy_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='special_events_form',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantlink',
            name='ubereats_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='last_verified',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='restaurantlink',
            name='url',
        ),
    ]
