# Generated by Django 4.2.23 on 2025-08-12 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subadmin', '0013_alter_restaurantlink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='subadmin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to=settings.AUTH_USER_MODEL),
        ),
    ]
