# Generated by Django 4.2.23 on 2025-08-12 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subadmin', '0014_alter_menu_subadmin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshour',
            name='subadmin_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to=settings.AUTH_USER_MODEL),
        ),
    ]
