# Generated by Django 4.2.23 on 2025-08-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0015_alter_businesshour_subadmin_profile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('menu', 'display_order'), name='unique_display_order_per_menu'),
        ),
    ]
