# Generated by Django 4.2.23 on 2025-08-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subadmin', '0016_menuitem_unique_display_order_per_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsfallbacksettings',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_fallback_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
