# Generated by Django 4.2.23 on 2025-08-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_subadminprofile_created_at'),
        ('subadmin', '0017_alter_smsfallbacksettings_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsfallbacksettings',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_fallback_settings', to='authentication.subadminprofile'),
        ),
    ]
