# Generated by Django 4.2.23 on 2025-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/subadmins/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/users/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subdir', 'SubAdmin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
