# Generated by Django 4.2.23 on 2025-07-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_subadminprofile_first_name_subadminprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadminprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subadminprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
