# Generated by Django 4.2.23 on 2025-07-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_subadminprofile_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subadminprofile',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
