# Generated by Django 4.2.23 on 2025-07-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_date_joined_subadminprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subadminprofile',
            name='created_at',
        ),
    ]
