# Generated by Django 4.2.23 on 2025-07-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_subadminprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
